app/urls.py
from django.conf.urls import url
from app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^event/(?P<event_id>[0-9]+)/$', views.event, name='event'),
    url(r'^ticket/(?P<ticket_id>[0-9]+)/$', views.ticket, name='ticket'),
    url(r'^invoice/(?P<invoice_id>[0-9]+)/$', views.invoice, name='invoice'),
    url(r'^invoice/pdf/(?P<owner_id>[0-9]+)/$', views.pdf, name='pdf'),
    url(r'^owner/(?P<owner_id>[0-9]+)/$', views.owner, name='owner'),
    url(r'^issuer/(?P<issuer_id>[0-9]+)/$', views.issuer, name='issuer'),
    url(r'^position/(?P<position_id>[0-9]+)/$', views.position, name='position'),
    url(r'^worker/(?P<worker_id>[0-9]+)/$', views.worker, name='worker'),
    url(r'^workers/$', views.workers, name='workers'),
    url(r'^positions/$', views.positions, name='positions'),
    url(r'^add/flat/$', views.add_flat, name='add_flat'),
    url(r'^flat/(?P<flat_id>[0-9]+)/$', views.flat, name='flat'),
    url(r'^flats/$', views.flats, name='flats'),
    url(r'^tickets/$', views.tickets, name='tickets'),
    url(r'^invoices/$', views.invoices, name='invoices'),
    url(r'^issuers/$', views.issuers, name='issuers'),
    url(r'^owners/$', views.owners, name='owners'),
    url(r'^add/event/$', views.add_event, name='add_event'),
    url(r'^add/ticket/$', views.add_ticket, name='add_ticket'),
    url(r'^add/invoice/$', views.add_invoice, name='add_invoice'),
    url(r'^add/issuer/$', views.add_issuer, name='add_issuer'),
    url(r'^add/owner/$', views.add_owner, name='add_owner'),
    url(r'^delete/(?P<del_id>[0-9]+)/$', views.delete, name='delete'),
    url(r'^add/counter_state/$', views.add_counter_state, name='add_counter_state'),
    url(r'^counters/$', views.counters, name='counters'),
    url(r'^add/counter/$', views.add_counter, name='add_counter'),
    url(r'^counter/(?P<counter_id>[0-9]+)/$', views.counter, name='counter'),
    url(r'^counter/states/$', views.counter_states, name='counter_states'),
    url(r'^counter/state/(?P<counter_state_id>[0-9]+)/$', views.counter_state, name='counter_state'),
    url(r'^add/worker/$', views.add_worker, name='add_worker'),
    url(r'^add/position/$', views.add_position, name='add_position'),
    url(r'^add/overtime/$', views.add_overtime, name='add_overtime'),
    url(r'^overtimes/$', views.overtimes, name='overtimes'),
    url(r'^overtime/(?P<overtime_id>[0-9]+)/$', views.overtime, name='overtime'),
    url(r'^address/(?P<address_id>[0-9]+)/$', views.address, name='address'),
    url(r'^addresses/$', views.addresses, name='addresses'),
    url(r'^add/address/$', views.add_address, name='add_address'),
    url(r'^building/(?P<building_id>[0-9]+)/$', views.building, name='building'),
    url(r'^buildings/$', views.buildings, name='buildings'),
    url(r'^add/building/$', views.add_building, name='add_building'),
    url(r'^add/building_address/$', views.add_building_address, name='add_building_address'),
    url(r'^building_addresses/$', views.building_addresses, name='building_addresses'),
    url(r'^building_address/(?P<building_address_id>[0-9]+)/$', views.building_address, name='building_address'),
    # url(r'^edit/worker/(?P<worker_id>[0-9]+)/$', views.edit_worker, name='add_worker'),
    url(r'^edit/position/(?P<position_id>[0-9]+)/$', views.edit_position, name='add_position'),
    url(r'^edit/overtime/(?P<overtime_id>[0-9]+)/$', views.edit_overtime, name='add_overtime'),
    url(r'^edit/counter/(?P<counter_id>[0-9]+)/$', views.edit_counter, name='add_counter'),
    url(r'^edit/counter_state/(?P<counter_state_id>[0-9]+)/$', views.edit_counter_state, name='add_counter_state'),
    url(r'^edit/event/(?P<event_id>[0-9]+)/$', views.edit_event, name='add_event'),
    url(r'^edit/ticket/(?P<ticket_id>[0-9]+)/$', views.edit_ticket, name='add_ticket'),
    url(r'^edit/invoice/(?P<invoice_id>[0-9]+)/$', views.edit_invoice, name='add_invoice'),
    url(r'^edit/issuer/(?P<issuer_id>[0-9]+)/$', views.edit_issuer, name='add_issuer'),
    url(r'^edit/owner/(?P<owner_id>[0-9]+)/$', views.edit_owner, name='add_owner'),
    url(r'^edit/address/(?P<address_id>[0-9]+)/$', views.edit_address, name='add_address'),
    url(r'^edit/building_address/(?P<building_address_id>[0-9]+)/$', views.edit_building_address, name='add_building_address'),
]

systemsm/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^', include('app.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout),
]

app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User, Group


class Adres(models.Model):
    id = models.AutoField(primary_key=True)
    kod_pocztowy = models.TextField()
    miasto = models.TextField()
    ulica = models.TextField()

    class Meta:
        db_table = 'adres'


class AdresBudynek(models.Model):
    id = models.AutoField(primary_key=True)
    kod_pocztowy = models.TextField()
    miasto = models.TextField()
    ulica = models.TextField()

    class Meta:
        db_table = 'adresbudynek'


class Budynek(models.Model):
    id = models.AutoField(primary_key=True)
    adres = models.ForeignKey('AdresBudynek', models.SET('usunieto'), db_column='adresbudynek', related_name='+')
    administrator = models.ForeignKey('Pracownik', models.SET('usunieto'), db_column='administrator', related_name='+')

    class Meta:
        db_table = 'budynek'


class Faktura(models.Model):
    id = models.AutoField(primary_key=True)
    wartosc_netto = models.FloatField()
    wystawca = models.ForeignKey('Wystawca', models.SET('usunieto'), db_column='wystawca', related_name='+')
    wlasciciel = models.ForeignKey('Wlasciciel', models.SET('usunieto'), db_column='wlasciciel', null=True, blank=True, related_name='+')

    class Meta:
        db_table = 'faktura'


class Mieszkanie(models.Model):
    id = models.AutoField(primary_key=True)
    budynek = models.ForeignKey('Budynek', models.SET('usunieto'), db_column='budynek', related_name='+')
    metraz = models.FloatField()
    liczba_pokoi = models.IntegerField()
    piwnica = models.BooleanField()
    nr_mieszkania = models.IntegerField()

    class Meta:
        db_table = 'mieszkanie'


class Nadgodziny(models.Model):
    id = models.AutoField(primary_key=True)
    pracownik = models.ForeignKey('Pracownik', models.SET('usunieto'), db_column='pracownik', related_name='+')
    ilosc = models.FloatField()

    class Meta:
        db_table = 'nadgodziny'


class Pracownik(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.SET('usunieto'), default=None, null=True, blank=True)
    stanowisko = models.ForeignKey('Stanowisko', models.SET('usunieto'), db_column='stanowisko', related_name='+')
    budynek = models.IntegerField(null=True, blank=True)
    imie = models.TextField()
    nazwisko = models.TextField()
    telefon = models.TextField()
    email = models.TextField()
    adres = models.ForeignKey('Adres', models.SET('usunieto'), db_column='adres', related_name='+')

    class Meta:
        db_table = 'pracownik'


class Licznik(models.Model):
    id = models.AutoField(primary_key=True)
    typ = models.TextField()
    cena_netto = models.FloatField()

    class Meta:
        db_table = 'licznik'


class StanLicznik(models.Model):
    id = models.AutoField(primary_key=True)
    typ = models.ForeignKey('Licznik', models.SET('usunieto'), db_column='typ', related_name='+')
    mieszkanie = models.ForeignKey('Mieszkanie', models.SET('usunieto'), db_column='mieszkanie', related_name='+')
    stan = models.FloatField()

    class Meta:
        db_table = 'stan_licznik'


class Stanowisko(models.Model):
    id = models.AutoField(primary_key=True)
    nazwa = models.TextField()
    pensja = models.IntegerField()
    group = models.OneToOneField(Group, on_delete=models.SET('usunieto'), default=None, null=True, blank=True)

    class Meta:
        db_table = 'stanowisko'


class Wlasciciel(models.Model):
    id = models.AutoField(primary_key=True)
    imie = models.TextField()
    nazwisko = models.TextField()
    telefon = models.TextField()
    email = models.TextField()
    mieszkanie = models.ForeignKey('Mieszkanie', models.SET('usunieto'), db_column='mieszkanie', blank=True, null=True, related_name='+')

    class Meta:
        db_table = 'wlasciciel'


class Ticket(models.Model):
    id = models.AutoField(primary_key=True)
    pracownik = models.TextField(null=True, blank=True)
    zglaszajacy = models.TextField(default=None, null=True, blank=True)
    opis = models.TextField()
    data = models.DateField(default=timezone.now, null=True, blank=True)

    class Meta:
        db_table = 'ticket'


class Wydarzenie(models.Model):
    id = models.AutoField(primary_key=True)
    nazwa = models.TextField()
    opis = models.TextField()
    data = models.DateField()
    budynek = models.ForeignKey('Budynek', models.SET('usunieto'), db_column='budynek', blank=True, null=True, related_name='+')

    class Meta:
        db_table = 'wydarzenie'


class Wystawca(models.Model):
    id = models.AutoField(primary_key=True)
    nazwa = models.TextField()
    kod_pocztowy = models.TextField()
    miasto = models.TextField()
    ulica = models.TextField()
    telefon = models.TextField()
    email = models.TextField()

    class Meta:
        db_table = 'wystawca'

app/templates/add_building_address.html
{% extends "base.html" %} 
{% block content %}
<form method="POST" class="post-form">
    {% csrf_token %}
    <div class="form-group">
        <input class="form-control" id="id kod_pocztowy" name="kod_pocztowy" placeholder="Kod pocztowy" required pattern="[0-9]{2}[ -][0-9]{3}"></input>
    </div>
    <div class="form-group">
        <input class="form-control" id="id miasto" name="miasto" placeholder="Miasto" required pattern="[A-Z][A-Za-z' -]+"></input>
    </div>
    <div class="form-group">
        <input class="form-control" id="id ulica" name="ulica" placeholder="Ulica" required pattern="[A-Z][A-Za-z' -]+"></input>
    </div>
    <button type="submit" class="btn btn-primary">Dodaj</button>
</form>

{% endblock content %}

app/templates/add_counter.html
{% extends "base.html" %} 
{% block content %}
<form method="POST" class="post-form">
    {% csrf_token %}
    <div class="form-group">
        <input class="form-control" id="id typ" name="typ" placeholder="Typ" required pattern="[A-Z][A-Za-z' -]+"></input>
    </div>
    <div class="form-group">
        <input class="form-control" id="id cena_netto" name="cena_netto" placeholder="Cena netto" required pattern="[0-9]+([\.,][0-9]+)?"></input>
    </div>
    <button type="submit" class="btn btn-primary">Dodaj</button>
</form>

{% endblock content %}

app/templates/add_counter_state.html
{% extends "base.html" %}

{% block content %}

<form method="POST" class="post-form">
    {% csrf_token %}
    <div class="form-group">
        <select name="typ" id="id typ" class="custom-select" required>
                <option selected disabled>Wybierz Typ</option>
                {% if counters_list %}
                {% for counters in counters_list %}
                <option value="{{ counters.id }}">{{ counters.typ }} | {{ counters.cena_netto }}</option>
                {% endfor %}
                {% endif %}
              </select>
    </div>
    <div class="form-group">
        <select name="mieszkanie" id="id mieszkanie" class="custom-select" required>
                <option selected disabled>Wybierz mieszkanie</option>
                {% if flat_list %}
                {% for flat in flat_list %}
                <option value="{{ flat.id }}">{{ flat.budynek.adres.miasto }} ul. {{ flat.budynek.adres.ulica }}/{{ flat.nr_mieszkania }}</option>
                {% endfor %}
                {% endif %}
              </select>
</div>   
    <div class="form-group">
        <input type="text" class="form-control" type="number" name="stan" step="any" required id="id_stan" placeholder="Stan" required pattern="[0-9]+">
    </div>
    <button type="submit" class="btn btn-primary">Dodaj</button>
</form>

{% endblock content %}

app/templates/add_invoice.html
{% extends "base.html" %}

{% block content %}
{% if this_item %}
<p>Edycja</P>
{% endif %}
<form method="POST" class="post-form">
    {% csrf_token %}
    <div class="form-group">
        <select name="wystawca" id="id wystawca" class="custom-select" required>
                {% if this_item %}
                <option selected value="{{ this_item.wystawca.id }}">{{ this_item.wystawca.nazwa }} | {{ this_item.wystawca.miasto }} ul. {{ this_item.wystawca.ulica }} (Nie zmieniaj)</option>
                {% else %}
                <option selected disabled>Wybierz wystawce</option>
                {% endif %}
                {% if issuers_list %}
                {% for issuer in issuers_list %}
                <option value="{{ issuer.id }}">{{ issuer.nazwa }} | {{ issuer.miasto }} ul. {{ issuer.ulica }}</option>
                {% endfor %}
                {% endif %}
              </select>
    </div>
    <div class="form-group">
        <select name="wlasciciel" id="id wlasciciel" class="custom-select" required>
                {% if this_item %}
                <option selected value="{{ this_item.wlasciciel.id }}">{{ this_item.wlasciciel.imie }} {{ this_item.wlasciciel.nazwisko }} | {{ this_item.wlasciciel.mieszkanie.budynek.adres.miasto }} ul. {{ this_item.wlasciciel.mieszkanie.budynek.adres.ulica }}/{{ this_item.wlasciciel.mieszkanie.nr_mieszkania }} (Nie zmieniaj)</option>
                {% else %}
                <option selected disabled>Wybierz mieszkańca</option>
                {% endif %}
                {% if owners_list %}
                {% for owner in owners_list %}
                <option value="{{ owner.id }}">{{ owner.imie }} {{ owner.nazwisko }} | {{ owner.mieszkanie.budynek.adres.miasto }} ul. {{ owner.mieszkanie.budynek.adres.ulica }}/{{ owner.mieszkanie.nr_mieszkania }}</option>
                {% endfor %}
                {% endif %}
              </select>
    </div>    
    <div class="form-group">
        <input type="text" class="form-control" type="number" name="wartosc_netto" step="any" required id="id_wartosc_netto" placeholder="Wartosc netto" required pattern="[0-9]+([\.,][0-9]+)?" value="{% if this_item %}{{ this_item.wartosc_netto }}{% endif %}">
    </div>
    <button type="submit" class="btn btn-primary">Dodaj</button>
</form>

{% endblock content %}

app/templates/add_owner.html
{% extends "base.html" %} 
{% block content %}
<form method="POST" class="post-form">
    {% csrf_token %}
    <div class="form-group">
        <input class="form-control" id="id imie" name="imie" placeholder="Imie" required pattern="[A-Z][A-Za-z]+"></input>
    </div>
    <div class="form-group">
        <input class="form-control" id="id nazwisko" name="nazwisko" placeholder="Nazwisko" required pattern="[A-Z][A-Za-z]+"></input>
    </div>
    <div class="form-group">
        <input class="form-control" id="id telefon" name="telefon" placeholder="Telefon" required pattern="[0-9]{9}"></input>
    </div>
    <div class="form-group">
        <input class="form-control" id="id email" name="email" placeholder="Email" required pattern="[A-Za-z0-9]+[@][A-Za-z.]+"></input>
    </div>
    <div class="form-group">
        <select name="mieszkanie" id="id mieszkanie" class="custom-select" required>
                <option selected disabled>Wybierz mieszkanie</option>
                {% if flat_list %}
                {% for flat in flat_list %}
                <option value="{{ flat.id }}">{{ flat.budynek.adres.miasto }} ul. {{ flat.budynek.adres.ulica }}/{{ flat.nr_mieszkania }}</option>
                {% endfor %}
                {% endif %}
              </select>
</div>
    <button type="submit" class="btn btn-primary">Dodaj</button>
</form>

{% endblock content %}

app/templates/add_position.html
{% extends "base.html" %} 
{% block content %}
<form method="POST" class="post-form">
    {% csrf_token %}
    <div class="form-group">
        <input class="form-control" id="id nazwa" name="nazwa" placeholder="Nazwa" required pattern="[A-Z][A-Za-z]+"></input>
    </div>
    <div class="form-group">
        <input class="form-control" id="id pensja" name="pensja" placeholder="Pensja" required pattern="[0-9]+"></input>
    </div>
    <button type="submit" class="btn btn-primary">Dodaj</button>
</form>

{% endblock content %}

app/templates/add_worker.html
{% extends "base.html" %}

{% block content %}

<form method="POST" class="post-form">
    {% csrf_token %}
    <div class="form-group">
        <select name="stanowisko" id="id stanowisko" class="custom-select" required>
                <option selected disabled>Wybierz stanowisko</option>
                {% if position_list %}
                {% for position in position_list %}
                <option value="{{ position.id }}">{{ position.nazwa }}</option>
                {% endfor %}
                {% endif %}
              </select>
    </div>
    <div class="form-group">
        <select name="adres" id="id adres" class="custom-select" required>
                <option selected disabled>Wybierz adres</option>
                {% if address_list %}
                {% for address in address_list %}
                <option value="{{ address.id }}">{{ address.kod_pocztowy }} {{ address.miasto }} ul. {{ address.ulica }}</option>
                {% endfor %}
                {% endif %}
              </select>
    </div>
    <div class="form-group">
        <input class="form-control" id="id imie" name="imie" placeholder="Imie" required pattern="[A-Z][A-Za-z]+"></input>
    </div>
    <div class="form-group">
        <input class="form-control" id="id nazwisko" name="nazwisko" placeholder="Nazwisko" required pattern="[A-Z][A-Za-z]+"></input>
    </div>
    <div class="form-group">
        <input class="form-control" id="id telefon" name="telefon" placeholder="Telefon" required pattern="[0-9]{9}"></input>
    </div>
    <div class="form-group">
        <input class="form-control" id="id email" name="email" placeholder="Email" required pattern="[A-Za-z0-9]+[@][A-Za-z.]+"></input>
    </div>
    <button type="submit" class="btn btn-primary">Dodaj</button>
</form>

{% endblock content %}

app/templates/addresses.html
{% extends "base.html" %}

{% block content %}

{% if address_list %}
{% for address in address_list %}
<li>Adres: <a href="/address/{{ address.id }}/">{{ address.miasto }}, ul. {{ address.ulica }}</a></li>
{% endfor %}
{% else %}
<li>Brak budynków</li>
{% endif %}

{% endblock content %}

app/templates/flat.html
{% extends "base.html" %}

{% block content %}

<li>Budynek: {{ entry.budynek.adres.miasto }}, ul. {{ entry.budynek.adres.ulica }}</li> 
<li>Metraż: {{ entry.metraz }} m</li>
<li>Liczba pokoi: {{ entry.liczba_pokoi }}</li> 
<li>Piwnica: {{ entry.piwnica }}</li> 
<li>Nr. mieszkania: {{ entry.nr_mieszkania }}</li> 
{% if user.is_authenticated %}
{% load app_filters %}
<form action="{% url 'delete' entry.id %}" method="POST">
    {% csrf_token %}
    <input type="hidden" value="{{ entry | to_class_name }}" name="name"></input>
    <button type="submit" class="btn btn-danger">Usuń</button>
</form>
{% endif %}

{% endblock content %}

app/templates/issuers.html
{% extends "base.html" %}

{% block content %}

{% if issuers_list %}
{% for issuer in issuers_list %}
<li><a href="/issuer/{{ issuer.id }}/">{{ issuer.nazwa }}</a>, {{ issuer.miasto }} ul. {{ issuer.ulica }}</li>
{% endfor %}
{% else %}
<li>Brak wystawców</li>
{% endif %}

{% endblock content %}

app/templates/messages.html
<div class="container">
    {% if messages %} {% for msg in messages %}
    <div class="alert alert-{{ msg.tags }} alert-dismissable fade show">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ msg.message|safe|linebreaksbr }}
    </div>
    {% endfor %} {% endif %}
</div>

app/templates/tickets.html
{% extends "base.html" %}

{% block content %}

{% if tickets_list %}
{% for ticket in tickets_list %}
<li><a href="/ticket/{{ ticket.id }}/">{{ ticket.opis|truncatechars:30 }}</a>, przez {{ ticket.zglaszajacy }}</li>
{% endfor %}
{% else %}
<li>Brak zgłoszeń</li>
{% endif %}

{% endblock content %}

<!-- my tickets -->

app/templates/worker.html
{% extends "base.html" %}

{% block content %}

<li>{{ entry.imie }} {{ entry.nazwisko }}</li>
<li>Stanowisko: {{ entry.stanowisko.nazwa }}, pensja: {{ entry.stanowisko.pensja }}</li>
<li>Telefon: {{ entry.telefon }}, e-mail: {{ entry.email }}</li>
<li>Adres: {{ entry.adres.kod_pocztowy }} {{ entry.adres.miasto }}, ul. {{ entry.adres.ulica }}</li>
{% if user.is_authenticated %}
{% load app_filters %}
<form action="{% url 'delete' entry.id %}" method="POST">
    {% csrf_token %}
    <input type="hidden" value="{{ entry | to_class_name }}" name="name"></input>
    <button type="submit" class="btn btn-danger">Usuń</button>
</form>
{% endif %}

{% endblock content %}

app/templates/workers.html
{% extends "base.html" %}

{% block content %}

{% if worker_list %}
{% for worker in worker_list %}
<li><a href="/worker/{{ worker.id }}/">{{ worker.imie }} {{ worker.nazwisko }}</a>, {{ worker.stanowisko.nazwa }}</li>
{% endfor %}
{% else %}
<li>Brak pracowników</li>
{% endif %}

{% endblock content %}